### ISSUE TITLE
terminal toolbar leak

### ISSUE THREAD

**Issue by yzhen123** [jeremyramin/terminal-plus#30] opened 2015-10-08 08:08 UTC
I use zsh as the terminal and it startups very slow, and sometimes maybe I double clicked those terminal icons without awareness, then create a new terminal, but some bugs happened... some terminal icon couldn't open but can be removed by contextmenu, but I find there are two toolbar in my terminal and sometimes there could be two terminal opened at the same time. 

![image](https://cloud.githubusercontent.com/assets/5233940/10360786/0387d8bc-6dd6-11e5-9ecb-396e5a5aa481.png)

**Comment by jeremyramin** [comment] 2015-10-08 08:35
If you could provide me with some more information, I can get to fixing this.
1. What program are you using to get zsh? I believe you are on a Windows computer.

This could be caused by a bug where the terminal view get's stuck waiting for the zsh to load.

**Comment by yzhen123** [comment] 2015-10-08 08:38
@jeremyramin I'm using msys2 and oh-my-zsh which slow down more, 
here are my config:
```coffee-script
  "terminal-plus":
    core:
      shell: "c:\\Windows\\System32\\cmd.exe"
      shellArguments: "/K \"zsh\""
```

**Comment by jeremyramin** [comment] 2015-10-09 20:29
I'll have to get msys2 and zsh on a Windows computer for testing. I'll keep you updated on my progress.

**Comment by yzhen123** [comment] 2015-10-09 23:38
I find out double click on the terminal icon would trigger this bug, maybe create new tab and open current tab confused the plugin, hoping would help.

**Comment by jeremyramin** [comment] 2015-10-11 19:36
Thanks for informing me of this. I will try and disable double clicks on the terminal icon to prevent this issue.

**Comment by jeremyramin** [comment] 2015-10-12 04:11
v0.8.1 should be patched to prevent the double click on status icons. Please give it a try and let me know if this fixes your issue.

**Comment by yzhen123** [comment] 2015-10-13 07:13
@jeremyramin  good job! it's fixed now.

**Comment by jeremyramin** [comment] 2015-10-13 15:36
Great! Closing this issue now that it has been fixed.

**Closed by jeremyramin** 2015-10-13 15:36 UTC
Labels: bug
