### ISSUE TITLE
scroll up does not work

### ISSUE THREAD

**Issue by siklodi-mariusz** [jeremyramin/terminal-plus#12] opened 2015-09-18 06:38 UTC
I can't scroll up to see previous commands and output. 
I can scoll up while a command is running for example ```rake``` and when the command is finished it freezes where It was and can't go down. 
**Ubuntu 14.04**
**Atom: 1.0.11**
**Terminal-plus: 0.4.2**

**Comment by jeremyramin** [comment] 2015-09-18 06:48
That is interesting, I see it working for me and it works on my Ubuntu machine. Please try updating Atom to the latest release (1.0.13) and then updating Terminal-Plus if you can.

**Comment by jeremyramin** [comment] 2015-09-21 20:34
Do you still have this issue?

**Comment by siklodi-mariusz** [comment] 2015-09-22 06:28
Yes it's still the same. But I didn't update Atom  yet. I've added the PPA from [here](https://launchpad.net/~webupd8team/+archive/ubuntu/atom/) but it's not updated that frequently. I'll wait until it's updated and see if things change.

**Comment by jeremyramin** [comment] 2015-09-22 23:40
Okay thanks, that would be great.

**Comment by davunderscorei** [comment] 2015-09-23 16:36
I'm getting the same issue frequently (but not constantly) on:

* OSX 10.10.2
* Atom 1.0.15
* terminal-plus 0.5.0

**Comment by jeremyramin** [comment] 2015-09-23 16:39
Are you using `rake` as well or is it a different command?

**Comment by davunderscorei** [comment] 2015-09-23 16:50
Nope not using `rake`, it seems to be all sorts of commands. I only started using Atom and terminal-plus today so I'll keep an eye on it and see if I can notice any patterns but so far seems to be random!

**Comment by jeremyramin** [comment] 2015-09-23 16:52
What is interesting is that it doesn't seem to be a widespread problem as far as I know. Please do let me know if you figure out what the correlation might be for these commands that cause a scrolling problem.

**Comment by davunderscorei** [comment] 2015-09-24 12:26
Not found a pattern yet, but I've found that if you run a long running command (e.g. `ping google.com`) then scrolling works again, until that command finishes, when scrolling no longer works.

**Comment by siklodi-mariusz** [comment] 2015-09-24 13:03
Yes that's exactly how it behaves. So for exemple if I run ```tail -f -n 10 <file>``` to monitor my ```rails``` project development.log, scroll works perfectly as long as the ```tail``` comand is running. When I stop the command it freezes.

**Comment by jeremyramin** [comment] 2015-09-24 17:00
I'm going to need someone to run some commands in the console and paste their output here so I can figure out what's wrong with the scrolling. At the very lease we know that the scroll event is received. It's just something is blocking you from scrolling once a command ends.  
```
atom.packages.getActivePackage('terminal-plus').mainModule.statusBar.getActiveTerminalView().terminal.rows;
atom.packages.getActivePackage('terminal-plus').mainModule.statusBar.getActiveTerminalView().terminal.ydisp;
atom.packages.getActivePackage('terminal-plus').mainModule.statusBar.getActiveTerminalView().terminal.ybase;
atom.packages.getActivePackage('terminal-plus').mainModule.statusBar.getActiveTerminalView().terminal.scrolling;
atom.packages.getActivePackage('terminal-plus').mainModule.statusBar.getActiveTerminalView().terminal.lines.length;
```
Unfortunately you can only do one command at a time to see the output. You can get to the developer console via: `View > Developer > Toggle Developer Tools` then click on the console tab of the view that comes up.

**Comment by davunderscorei** [comment] 2015-09-25 08:35
> atom.packages.getActivePackage('terminal-plus').mainModule.statusBar.getActiveTerminalView().terminal.rows;
    < 17
    > atom.packages.getActivePackage('terminal-plus').mainModule.statusBar.getActiveTerminalView().terminal.ydisp;
    < 21
    > atom.packages.getActivePackage('terminal-plus').mainModule.statusBar.getActiveTerminalView().terminal.ydisp;
    < 21
    > atom.packages.getActivePackage('terminal-plus').mainModule.statusBar.getActiveTerminalView().terminal.scrolling;
    < false
    > atom.packages.getActivePackage('terminal-plus').mainModule.statusBar.getActiveTerminalView().terminal.lines.length;
    < 38

**Comment by siklodi-mariusz** [comment] 2015-09-25 08:57
```
> atom.packages.getActivePackage('terminal-plus').mainModule.statusBar.getActiveTerminalView().terminal.rows;
=> 15

> atom.packages.getActivePackage('terminal-plus').mainModule.statusBar.getActiveTerminalView().terminal.ydisp;
=> 0

> atom.packages.getActivePackage('terminal-plus').mainModule.statusBar.getActiveTerminalView().terminal.ybase;
=> 0

> atom.packages.getActivePackage('terminal-plus').mainModule.statusBar.getActiveTerminalView().terminal.scrolling;
=> false

> atom.packages.getActivePackage('terminal-plus').mainModule.statusBar.getActiveTerminalView().terminal.lines.length;
=> 15
```

**Comment by jeremyramin** [comment] 2015-09-26 01:21
@davunderscorei Were you at the bottom after running a command?
@siklodi-mariusz I think you didn't have any history to scroll at that point.

**Comment by davunderscorei** [comment] 2015-09-28 08:55
@jeremyramin I was yes.

I've also thought of something else - I am using ZSH as my shell. I used `chsh` to switch to `bash` and then scrolling works.

@siklodi-mariusz are you using `bash` or another shell such as ZSH?

**Comment by siklodi-mariusz** [comment] 2015-09-28 09:30
Yes I'm using ZSH.

These are the results from the commands with some history.
```
> atom.packages.getActivePackage('terminal-plus').mainModule.statusBar.getActiveTerminalView().terminal.rows;
=> 15
> atom.packages.getActivePackage('terminal-plus').mainModule.statusBar.getActiveTerminalView().terminal.ydisp;
=> 293
> atom.packages.getActivePackage('terminal-plus').mainModule.statusBar.getActiveTerminalView().terminal.ybase;
=> 293
> atom.packages.getActivePackage('terminal-plus').mainModule.statusBar.getActiveTerminalView().terminal.scrolling;
=> false
> atom.packages.getActivePackage('terminal-plus').mainModule.statusBar.getActiveTerminalView().terminal.lines.length;
=> 309
```

**Comment by jeremyramin** [comment] 2015-09-28 15:23
That could very well be the issue. Thank you, I'll try and recreate the
issue when I have a chance. You'll be notified once an update with the fix
has been released.

**Comment by davunderscorei** [comment] 2015-09-29 08:25
Cool, thanks @jeremyramin.

**Comment by jeremyramin** [comment] 2015-09-30 00:01
So I've been using zsh as my main shell for the past day, and scrolling seems to be working fine with me. This is rather peculiar...

**Comment by davunderscorei** [comment] 2015-09-30 08:27
@jeremyramin Scrolling seems normal when a command is running.

**Comment by jeremyramin** [comment] 2015-10-06 05:11
I'm inclined to believe that there is some customization of zsh that you two have. I have no modifications to my zsh and it works perfectly fine. I'm not entirely familiar with what you can do with zsh, but is it possible that you have some modification to the standard functionality of it?

**Comment by siklodi-mariusz** [comment] 2015-10-06 06:48
Well other than this list of enabled plugins 
```plugins=(git postgres ubuntu rvm rails bundler atom)```
in my ```~/.zshrc``` file. 
I haven't done anything.

**Comment by jeremyramin** [comment] 2015-10-06 07:00
@siklodi-mariusz This was the issue! I can finally not scroll on my system. I'll work on fixing this now.

**Comment by jeremyramin** [comment] 2015-10-06 07:23
@siklodi-mariusz The latest release (v0.6.4) should fix this issue. Please give it a try when you have a chance :)

**Comment by siklodi-mariusz** [comment] 2015-10-06 07:26
Great, thank you! I'll update and let you know.

**Comment by siklodi-mariusz** [comment] 2015-10-06 07:32
Yes it works. Great work @jeremyramin ! Thank you very much. You just made my working environment much better.

**Comment by jeremyramin** [comment] 2015-10-06 07:35
@siklodi-mariusz No problem. I'm glad you like the package. Sorry it took so long to get a fix, I've been rather busy lately.

**Comment by davunderscorei** [comment] 2015-10-08 10:19
@jeremyramin I can confirm the latest release works for me too. Thanks so much for your time and effort. What was the commit that you fixed it in?

**Comment by jeremyramin** [comment] 2015-10-08 17:30
@davunderscorei I'm glad it works for you. It was an issue with the term.js dependency of Terminal-Plus. I have a fork of the dependency so I can make changes and fix bugs as they arise.

Commit: jeremyramin/term.js#5d74aa1dc5a57303d48396b6ad3a6a6bdac5b842

**Comment by jeremyramin** [comment] 2015-10-08 17:40
Now that two people can confirm that this issue has been fixed, I will now close the issue.

**Closed by jeremyramin** 2015-10-08 17:40 UTC
Labels: bug
