### ISSUE TITLE
Mac atom 1.25.0 X64 can not input anything

### ISSUE THREAD

**Issue by AzeWZ** [jeremyramin/terminal-plus#537] opened 2018-04-02 05:10 UTC
Mac atom 1.25.0 X64 can not input anything

**Comment by 3dos** [comment] 2018-04-17 11:34
Same here :/

**Comment by Davisa94** [comment] 2018-05-02 18:44
Same issue but in windows ten

**Comment by uscitp-rsokolov** [comment] 2018-05-04 00:25
+1 same issue here

**Comment by kunzeal** [comment] 2018-05-08 07:26
+1

**Comment by bjce** [comment] 2018-05-10 14:58
Same issue with atom 1.26.1
and I think this issue is a duplicate of that issue [https://github.com/jeremyramin/terminal-plus/issues/525](url)

**Comment by rythod** [comment] 2018-05-13 07:06
+1 same issue.  really hope this is fixed soon, I love this IDE and terminal-plus is like the cherry on top

**Comment by Rhiana** [comment] 2018-05-14 04:30
same issue, just installed it today on an up to date atom on osx and can't input anyhting

**Comment by Stedders** [comment] 2018-05-14 13:29
+1 

Atom 1.26.1 x64, Mac OS 10.13.4.

**Comment by Liudongge** [comment] 2018-05-25 08:14
+1
Atom 1.27.1 x64, Mac OS 10.13.3
after installed it today

**Comment by logopogo** [comment] 2018-05-28 05:53
+1

**Comment by bjce** [comment] 2018-06-16 15:19
I just find a possible alternative for people using `Hydrogen`. It's called `Hydrogen-launcher`. Here is the link:
[https://github.com/lgeiger/hydrogen-launcher](url)

I had to run the following lines in Terminal first (taken from this github page: [https://github.com/nteract/hydrogen/issues/243](url) 

$ sudo apt autoremove ipython
$ sudo apt install python-pip -y
$ pip install --upgrade pip

then, install ipython[notebook]

$ sudo pip install ipython[notebook]

But then it worked fine

**Closed as completed** 2023-06-19 07:59 UTC
