### ISSUE TITLE
cursor does not always change to indicate window is not active

### ISSUE THREAD

**Issue by MarkZander** [jeremyramin/terminal-plus#55] opened 2015-10-26 17:31 UTC
When clicking on another window the cursor in terminal-plus continues to blink, it is blinking now while I'm entering this text. I'm frequently confused and forget to click on the terminal-plus pane before typing making for interesting results in unexpected windows.

Thanks for terminal-plus. It's great having an integrated terminal in atom.

**Comment by jeremyramin** [comment] 2015-10-26 20:45
Thank you for using Terminal-Plus. You are right, it should disable the cursor when the window is not in focus. I have fixed this issue and pushed up the changes. Expect the next update to fix the cursor blink. 

If you still have this problem after the next update, please let me know. Otherwise go ahead and close this issue if it has been resolved.

**Comment by MarkZander** [comment] 2015-10-26 22:06
Thanks for looking into this and thanks again for the use of your software.

Mark

**Comment by jeremyramin** [comment] 2015-10-27 20:03
Fixed as of v0.12.3

**Comment by MarkZander** [comment] 2015-10-27 20:32
Much better!  Thanks!

However, the cursor is blinking when I click on tree view and when I type it does not go to the terminal-plus. In all other cases it does the right thing. It is workable for me as is.

Mark

**Comment by jeremyramin** [comment] 2015-10-27 20:37
That is interesting. I do have it set up to stop blinking when clicking any other part of Atom. There is no reason that it shouldn't work for the tree view. I will have to look into why this happens.

**Comment by MarkZander** [comment] 2015-10-27 22:24
It works fine for me as is.

I wonder if the problem is with atom itself?

Thanks for fixing.

Mark

**Comment by jeremyramin** [comment] 2015-10-28 00:34
The problem is with Atom. As seen [here](https://github.com/atom/tree-view/blob/master/lib/tree-view.coffee#L702) in the tree-view repository, Atom stops the propagation of the click event on the tree-view. I use the click event to blur the terminal if people click outside of the terminal. Since Atom stops the event after they process it, the terminal never sees that the click event happened. Not much I can do about this. I tried to work around it, but no luck.

Hopefully the tree-view issue can be overlooked. Sorry about this.

**Comment by MarkZander** [comment] 2015-10-28 03:45
Yea, I don’t click there a lot anyway, what you got now is a great improvement.

Thanks, Mark

**Comment by jeremyramin** [comment] 2015-10-28 16:11
No problem. Closing this issue as it has been fixed by v0.12.3

**Closed by jeremyramin** 2015-10-28 16:11 UTC
Labels: bug
