### ISSUE TITLE
Uncaught Error: Cannot send message to terminated process

### ISSUE THREAD

**Issue by jibreel** [jeremyramin/terminal-plus#38] opened 2015-10-15 15:01 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package, v0.8.2

### Stack Trace

Uncaught Error: Cannot send message to terminated process

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:120

Error: Cannot send message to terminated process
  at Task.module.exports.Task.send (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:120:15)
  at TerminalPlusView.module.exports.TerminalPlusView.resize (/Users/jibreel/.atom/packages/terminal-plus/lib/view.coffee:223:6)
  at TerminalPlusView.module.exports.TerminalPlusView.resizeTerminalToView (/Users/jibreel/.atom/packages/terminal-plus/lib/view.coffee:350:5)
  at TerminalPlusView.module.exports.TerminalPlusView.focus (/Users/jibreel/.atom/packages/terminal-plus/lib/view.coffee:329:20)
  at HTMLDivElement.<anonymous> (/Users/jibreel/.atom/packages/terminal-plus/lib/view.coffee:1:1)
  at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
 10x -2:36.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:32.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:26.6.0 core:save (atom-text-editor.editor.is-focused)
     -2:07.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.13
file-icons, v1.6.10
latex, v0.26.0
tabs-to-spaces, v0.11.1
terminal-plus, v0.8.2

# Dev
No dev packages
```

**Comment by jeremyramin** [comment] 2015-10-15 19:07
Duplicate of #33

**Closed by jeremyramin** 2015-10-15 19:07 UTC
