### ISSUE TITLE
Uncaught TypeError: Cannot read property '24' of undefined

### ISSUE THREAD

**Issue by brianbolt** [jeremyramin/terminal-plus#87] opened 2015-11-14 00:31 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package, v0.14.1

### Stack Trace

Uncaught TypeError: Cannot read property '24' of undefined

```
At /Users/bbolt/.atom/packages/terminal-plus/node_modules/term.js/src/term.js:5354

TypeError: Cannot read property '24' of undefined
    at Terminal.clearSelectedText (/Users/bbolt/.atom/packages/terminal-plus/node_modules/term.js/src/term.js:5354:26)
    at HTMLDivElement.<anonymous> (/Users/bbolt/.atom/packages/terminal-plus/node_modules/term.js/src/term.js:949:12)
```

### Commands

```
  2x -6:48.2.0 terminal-plus:toggle (atom-text-editor.editor.is-focused)
  2x -6:43.9.0 core:close (textarea.)
     -6:26 terminal-plus:toggle (ul.list-inline.status-container)
  2x -6:06.7.0 terminal-plus:copy (textarea.)
  2x -5:59.9.0 terminal-plus:paste (textarea.)
  2x -5:02.9.0 terminal-plus:copy (textarea.)
     -5:01.7.0 terminal-plus:paste (textarea.)
  8x -4:30 core:copy (atom-text-editor.editor.is-focused)
     -4:25.4.0 terminal-plus:paste (textarea.)
  6x -2:57.2.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:32.9.0 core:copy (atom-text-editor.editor.is-focused)
     -2:31.8.0 terminal-plus:paste (textarea.)
     -2:24.2.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -2:19.5.0 core:copy (atom-text-editor.editor.is-focused)
     -2:00.8.0 terminal-plus:paste (textarea.)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "terminal-plus": {
    "core": {
      "mapTerminalsToAutoOpen": true
    },
    "style": {}
  }
}
```

### Installed Packages

```coffee
# User
compare-files, v0.6.2
language-docker, v1.1.3
language-r, v0.4.0
remote-edit, v1.8.22
terminal-plus, v0.14.1

# Dev
No dev packages
```

**Comment by jeremyramin** [comment] 2015-11-14 19:36
Duplicate of #80. Closing in favor of previous issue.

**Closed by jeremyramin** 2015-11-14 19:36 UTC
