### ISSUE TITLE
Search in for Terminal

### ISSUE THREAD

**Issue by JohnRoach** [jeremyramin/terminal-plus#47] opened 2015-10-22 14:54 UTC
I sometimes have to scroll through a lot in the terminal. It would be most helpful if we can do search in the terminal.

**Comment by jeremyramin** [comment] 2015-10-22 20:20
Duplicate of #44. I have taken note that you need searching in the terminal as well. Please follow #44 for updates on the status of the feature. I will notify that issue thread once there is a release containing the ability to search.

**Closed by jeremyramin** 2015-10-22 20:20 UTC
